### ISSUE TITLE
Some abnormality

### ISSUE THREAD

**Issue by tuzhih** [vossjo/libbeef#2]
when i make BEEF-vdw to the VASP, I add "-Lproperpath(my path) -lbeef "to the library linker flags,then some error happened, that show can't find -lbeef. After that i change the statement  "-Lproperpath(my path) -lbeef " to "properpath(my path)",then it can be make to the VASP.Is it normal ?

**Comment by vossjo** [comment]
The argument after -L should be the path of the directory containing libbeef.a, i.e. the argument of -L itself should not contain the name libbeef.a (I assume it does in the above example since just specifying the path above "properpath(my path)" seemed to have worked for building vasp).
