### ISSUE TITLE
Which tag for using BEEF-vdW

### ISSUE THREAD

**Issue by zhiyuwang0911** [vossjo/libbeef#6]
Hi, if we already installed the package. What tag I should use to specify BEEF-vdW in mty INCAR. Thanks!

**Comment by TTsangSC** [comment]
Hi Zhiyu, you can minimally supply [`GGA = BF`](https://www.vasp.at/wiki/index.php/GGA) in the `INCAR` file to use BEEF-vdW. Alternatively, if you're using [`ase`](https://gitlab.com/ase/ase) to stage your calculations, you can supply the `xc='beef-vdw'` parameter to the `ase.calculators.vasp.Vasp` calculator object, which sets the value of `GGA`, `LUSE_VDW`, and [`ZAB_VDW`](https://www.vasp.at/wiki/index.php/ZAB_VDW) to appropriate values.

**Comment by vossjo** [comment]
@TTsangSC Yes, ase will set up all the vdW-related flags. When creating an INCAR by hand, besides GGA=BF, make sure to specify all of the below in INCAR
```
GGA = BF
LUSE_VDW = .TRUE.
Zab_VDW = -1.8867
```
Also note that we developed new improved machine-learned xc functionals for catalysis, including one with optimized vdW interactions. Fortran code [here](https://github.com/vossgroup/CML) and instructions how to use these further optimized functionals via libxc in VASP [here](https://vossgroup.sites.stanford.edu/methods).
